version: '3.7'

services:
  mongodb:
    image: mongo:${MONGODB_VERSION}
    environment:
        MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
        MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
        TZ: "$TZ"
    volumes:
      - ${MONGODB_DATA_DIR}:/data/db:rw
      - ${MONGODB_DATA_DIR}/mongo_key:/mongo:rw
    restart: always
    ports:
       - "${MONGODB_HOST_PORT}:27017"
    networks:
       - default
    command:
       --auth

  adminmongo:
    image: mrvautin/adminmongo
    depends_on:
      - mongodb
    ports:
      - "${ADMINMONGO_HOST_PORT}:1234"
    environment:
      HOST: "${ADMINMONGO_HOST}"
      DB_HOST: "${ADMINMONGO_DB_HOST}"
      DB_PORT: "${ADMINMONGO_DB_PORT}"
      DB_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      DB_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
    networks:
      - default